# Generated by Django 5.2.7 on 2025-11-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0002_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiditem',
            name='date',
        ),
    ]
