# Generated by Django 5.2.7 on 2025-11-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0003_remove_paiditem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deliver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vegetables.delivery'),
            preserve_default=False,
        ),
    ]
