# Generated by Django 5.2.7 on 2025-11-05 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0005_alter_payment_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetables.delivery'),
        ),
    ]
