# Generated by Django 5.2.7 on 2025-11-18 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vegetables.vegetables'),
        ),
    ]
