# Generated by Django 5.2.7 on 2025-11-18 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0009_alter_paiditem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiditem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetables.vegetables'),
        ),
    ]
