# Generated by Django 5.2.7 on 2025-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0010_alter_paiditem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiditem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_items/'),
        ),
        migrations.AddField(
            model_name='paiditem',
            name='product_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiditem',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
