# Generated by Django 5.2.7 on 2025-11-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0011_paiditem_product_image_paiditem_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
